In [51]:
#############################---Exercise 1 Start---####################################
import numpy as np

X =   [[ 0.9573075 ,  0.83877059,  1.51767182],
       [ 0.83782936, -0.88288659,  0.7371596 ],
       [-0.01786695,  0.83195016,  0.66394427],
       [-2.43495362, -0.5999003 , -1.40044824],
       [-0.67749399, -0.93229581,  0.4736418 ],
       [ 0.47934903,  0.90244159, -0.24246888],
       [ 1.00280715, -0.68745287, -1.08115248],
       [ 0.98143632,  0.77163722,  0.07051186],
       [ 1.10721349,  0.37520477,  0.54710493],
       [ 0.20813717, -0.56000733, -0.38301232]]

NUM_COLS = len(X[0])
NUM_ROWS = len(X)

def meanWithoutVectorization(X):
  columnTotals = [0] * NUM_COLS
  for i in range(NUM_COLS):
    for j in range(NUM_ROWS):
      columnTotals[i] += X[j][i]
  
  print("Mean Without Vectorization")
  for i in range(len(columnTotals)):
    print("\tColumn " + str(i) + " mean = " + str(columnTotals[i] / NUM_ROWS))

def meanWithVectorization(X):
  x = np.array(X)
  print("Mean With Vectorization")
  means = x.mean(axis=0)
  print("\tColumn 0 mean = " + str(means[0]))
  print("\tColumn 1 mean = " + str(means[1]))
  print("\tColumn 2 mean = " + str(means[2]))

meanWithoutVectorization(X)
meanWithVectorization(X)


######################################################################################

Mean Without Vectorization
	Column 0 mean = 0.24437654600000003
	Column 1 mean = 0.005746142999999993
	Column 2 mean = 0.09029523599999997
Mean With Vectorization
	Column 0 mean = 0.24437654600000003
	Column 1 mean = 0.005746142999999993
	Column 2 mean = 0.09029523599999997


In [52]:
#############################---Exercise 2 Start---####################################
import numpy as np

A =   [[-0.92597499,  0.43720423, -0.35210601],
       [-1.57649123, -1.07509224,  0.47516471],
       [-0.20934054,  1.02077567,  1.07644301],
       [-0.15567112, -2.55700368, -1.46401899],
       [ 0.02719893,  0.19837065,  1.85917993],
       [-0.48220856, -0.5882894 ,  0.8520666 ],
       [-0.61637754, -1.28843955,  0.21051033],
       [-0.37856032, -0.18264039, -1.66748906],
       [-1.88442764,  1.06363804, -0.73199025],
       [ 1.1067878 , -1.50124564,  0.3577191 ]]

B =   [[-0.92597499,  0.43720423, -0.35210601],
       [-1.57649123, -1.07509224,  0.47516471],
       [-0.20934054,  1.02077567,  1.07644301],
       [-0.15567112, -2.55700368, -1.46401899],
       [ 0.02719893,  0.19837065,  1.85917993],
       [-0.48220856, -0.5882894 ,  0.8520666 ],
       [-0.61637754, -1.28843955,  0.21051033],
       [-0.37856032, -0.18264039, -1.66748906],
       [-1.88442764,  1.06363804, -0.73199025],
       [ 1.1067878 , -1.50124564,  0.3577191 ]]

def addWithoutVectorization():
  C = []
  for i in range(len(A)): # for every row
    C.append([])
    for j in range(len(A[0])): # for every column
      newSum = A[i][j] + B[i][j]
      C[i].append(newSum)
  
  print("---Addition Without vectorization---")
  print(C)

def addWithVectorization():
  a_array = np.array(A)
  b_array = np.array(B)
  C = np.add(a_array, b_array)
  print("---Addition Without vectorization---")
  print(C)

addWithoutVectorization()
addWithVectorization()


######################################################################################

---Addition Without vectorization---
[[-1.85194998, 0.87440846, -0.70421202], [-3.15298246, -2.15018448, 0.95032942], [-0.41868108, 2.04155134, 2.15288602], [-0.31134224, -5.11400736, -2.92803798], [0.05439786, 0.3967413, 3.71835986], [-0.96441712, -1.1765788, 1.7041332], [-1.23275508, -2.5768791, 0.42102066], [-0.75712064, -0.36528078, -3.33497812], [-3.76885528, 2.12727608, -1.4639805], [2.2135756, -3.00249128, 0.7154382]]
---Addition Without vectorization---
[[-1.85194998  0.87440846 -0.70421202]
 [-3.15298246 -2.15018448  0.95032942]
 [-0.41868108  2.04155134  2.15288602]
 [-0.31134224 -5.11400736 -2.92803798]
 [ 0.05439786  0.3967413   3.71835986]
 [-0.96441712 -1.1765788   1.7041332 ]
 [-1.23275508 -2.5768791   0.42102066]
 [-0.75712064 -0.36528078 -3.33497812]
 [-3.76885528  2.12727608 -1.4639805 ]
 [ 2.2135756  -3.00249128  0.7154382 ]]


In [53]:
#############################---Exercise 3 Start---####################################
import numpy as np

a = [4, 2, 6, 2, 5, 7, 5, 8, 8, 4]
b = [4, 2, 6, 2, 5, 7, 5, 8, 8, 4]

def dotProductWithoutVectorization():
  dotProduct = 0
  for i in range(len(a)):
    dotProduct += (a[i] * b[i])  
  print("---Dot Product Without vectorization---")
  print(dotProduct)

def dotProductWithVectorization():
  a_vector = np.array(a)
  b_vector = np.array(b)
  npDotProduct = np.dot(a_vector, b_vector)
  print("---Dot Product With vectorization---")
  print(npDotProduct)

dotProductWithoutVectorization()
dotProductWithVectorization()


######################################################################################

---Dot Product Without vectorization---
303
---Dot Product With vectorization---
303


In [54]:
#############################---Exercise 4 Start---####################################
import numpy as np

a = [[1, 2], [2, 1]]
b = [[3], [1]]

def matMulWithoutVectorization():
    newMatrixRows = len(a)
    newMatrixCols = len(b[0])
    resultMatMulMatrix = []

    for i in range(len(a)):  # every row in a
        for j in range(len(b[0])):  # every col in b
            runningTally = 0
            for k in range(len(b)):  # every row in b
                runningTally += a[i][k] * b[k][j]
            resultMatMulMatrix.append([runningTally])

    print("---Matrix Multiplication Without Vectorization---")
    print(resultMatMulMatrix)


def matMulWithVectorization():
    a_matrix = np.array(a)
    b_matrix = np.array(b)
    matrixMultiplicationResult = np.matmul(a_matrix, b_matrix)
    print("---Matrix Multiplication With Vectorization---")
    print(matrixMultiplicationResult)


matMulWithoutVectorization()
matMulWithVectorization()

######################################################################################

---Matrix Multiplication Without Vectorization---
[[5], [7]]
---Matrix Multiplication With Vectorization---
[[5]
 [7]]
